service: seek-asia-backend 

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: ap-southeast-1	

functions:
  app:
    handler: server.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

plugins:
  - serverless-offline
